extends Node
class_name OVRInput

enum {
	TRIGGER_BUTTON = JOY_VR_TRIGGER
	GRIP_BUTTON = JOY_VR_GRIP
	AX_BUTTON = JOY_OCULUS_AX,
	BY_BUTTON = JOY_OCULUS_BY,
	THUMBSTICK_BUTTON = JOY_VR_PAD,
	MENU_BUTTON = JOY_OCULUS_MENU
}

enum {
	HORIZONTAL_AXIS = JOY_OPENVR_TOUCHPADX,
	VERTICAL_AXIS = JOY_OPENVR_TOUCHPADY
	TRIGGER_AXIS = JOY_VR_ANALOG_TRIGGER
}

enum {
	LEFT_DEVICE_ID = 0,
	RIGHT_DEVICE_ID = 1
}

enum Buttons {
	TRIGGER = TRIGGER_BUTTON,
	GRIP = GRIP_BUTTON,
	AX = AX_BUTTON,
	BY = BY_BUTTON,
	THUMBSTICK = THUMBSTICK_BUTTON
}

enum Axis {
	HORIZONTAL = HORIZONTAL_AXIS,
	VERTICAL = VERTICAL_AXIS,
	TRIGGER = TRIGGER_AXIS
}

enum DeviceID {
	LEFT = LEFT_DEVICE_ID,
	RIGHT = RIGHT_DEVICE_ID
}
